### ISSUE TITLE
No module named 'blip_utils'

### ISSUE THREAD

**Issue by Lotsoliu** [zjukg/Structure-CLIP#1]
Hi, I'm new to this task, it seems not work without blip_utils package, but I don't know where to get it. 

Traceback (most recent call last):
  File "./model/train.py", line 7, in <module>
    from utils import get_args, set_manualSeed, image_transform, WinoLoss, CLIPLoss, MarginLoss

    from blip_utils import get_rank, all_gather_batch
ModuleNotFoundError: No module named 'blip_utils'

**Comment by Lotsoliu** [comment]
![image](https://github.com/zjukg/Structure-CLIP/assets/127647910/421aecc0-f5f5-474e-9b42-a1de3dad8197)

**Comment by BigHyf** [comment]
> ![image](https://private-user-images.githubusercontent.com/127647910/294640878-421aecc0-f5f5-474e-9b42-a1de3dad8197.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1MTM3MTMsIm5iZiI6MTcwNDUxMzQxMywicGF0aCI6Ii8xMjc2NDc5MTAvMjk0NjQwODc4LTQyMWFlY2MwLWY1ZjUtNDc0ZS05YjQyLWExZGUzZGFkODE5Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNlQwMzU2NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNzQ3YzQ2YWUxODczNzI2NzA0NjA2M2NmYmJiZTEwNWFjMzI2MzQ3OGRlYzQyYmI3NzM0NjYzNWE3MmIxNTM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BHGymu_DNDvPQ-P5Y5pilPSJF3dKjpBkxbdNcgENrrk)

Thanks for your attention, we don't use CLIPLoss in utils.py, so we don't need to use from blip_utils import get_rank, all_gather_batch. In the future, I will carefully organize the code and remove the irrelevant parts of the code.

**Comment by Lotsoliu** [comment]
thanks a lot!

**Comment by wdi-nancy** [comment]
> > ![image](https://private-user-images.githubusercontent.com/127647910/294640878-421aecc0-f5f5-474e-9b42-a1de3dad8197.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1MTM3MTMsIm5iZiI6MTcwNDUxMzQxMywicGF0aCI6Ii8xMjc2NDc5MTAvMjk0NjQwODc4LTQyMWFlY2MwLWY1ZjUtNDc0ZS05YjQyLWExZGUzZGFkODE5Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNlQwMzU2NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNzQ3YzQ2YWUxODczNzI2NzA0NjA2M2NmYmJiZTEwNWFjMzI2MzQ3OGRlYzQyYmI3NzM0NjYzNWE3MmIxNTM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BHGymu_DNDvPQ-P5Y5pilPSJF3dKjpBkxbdNcgENrrk)
> 
> Thanks for your attention, we don't use CLIPLoss in utils.py, so we don't need to use from blip_utils import get_rank, all_gather_batch. In the future, I will carefully organize the code and remove the irrelevant parts of the code.

请问作者为什么不用CLIPLoss了呢？因为论文里提到：in order to maintain the general representation ability of the model, we combine the original mini-batch image-text contrastive learning loss and the proposed loss for joint training. 删掉CLIPLoss之后，如何维持general representation ability？以及有什么实验去证明这个能力，因为从表格看貌似只有在vg上做relation和attribution的下游任务结果。
