### ISSUE TITLE
experimental procedure

### ISSUE THREAD

**Issue by ghost** [zjukg/Structure-CLIP#10]
Could you please give me a copy of the experimental procedure? The names of the data sets are a little confusing, thank you.

**Comment by BigHyf** [comment]
你好 你可以run.sh作为入口来看这个代码，如果你对整个流程有疑问的话，我建议您这边可以先去看一下ICLR2023的negCLIP

**Comment by ghost** [comment]
非常感谢分享！







---- Replied Message ----
| From | Yufeng ***@***.***> |
| Date | 4/20/2024 09:51 |
| To | ***@***.***> |
| Cc | ***@***.***>,
***@***.***> |
| Subject | Re: [zjukg/Structure-CLIP] experimental procedure (Issue #10) |

你好 你可以run.sh作为入口来看这个代码，如果你对整个流程有疑问的话，我建议您这边可以先去看一下ICLR2023的negCLIP
