### ISSUE TITLE
myTransformer bert_Transformer

### ISSUE THREAD

**Issue by zynlp1999** [zjukg/Structure-CLIP#11]
Hello, I am very interested in your article. To repeat your comparison experiment, triple_Transformer myTransformer bert_Transformer. There are many problems when changing myTransformer bert_Transformer, how should I operate it? Thank you for your reading.

**Comment by BigHyf** [comment]
> Hello, I am very interested in your article. To repeat your comparison experiment, triple_Transformer myTransformer bert_Transformer. There are many problems when changing myTransformer bert_Transformer, how should I operate it? Thank you for your reading.

你好，感谢你关注我们的工作，我们论文中用到的应该只有triple transformer，也就是主程序里引用的部分，triple transformer和my transformer是之前的一些尝试，在最终的实验代码里面并没有用到。

**Comment by zynlp1999** [comment]
好的好的，非常感谢您的回复，想再问一下，如果我想跑没有语义负样本的可以直接把neg_loss的比例设置为0吗，这样就算没有语义负样本的了吗？非常感谢您

**Comment by BigHyf** [comment]
> 好的好的，非常感谢您的回复，想再问一下，如果我想跑没有语义负样本的可以直接把neg_loss的比例设置为0吗，这样就算没有语义负样本的了吗？非常感谢您

你可以试一试，但我印象里如果没有语义负样本的话在下游数据集上的效果挺差的。我们这片工作的核心就是在语义负样本这一块。

**Comment by zynlp1999** [comment]
好的好的谢谢您 那想问下您的代码中是怎么实现没有语义负样本呢的实验呢
