### ISSUE TITLE
IR-R@1 TR-R@1结果

### ISSUE THREAD

**Issue by zynlp1999** [zjukg/Structure-CLIP#12]
您好作者，想问下IR-R@1 TR-R@1结果复现不到论文这么高 差十多正常吗

**Comment by BigHyf** [comment]
> 您好作者，想问下IR-R@1 TR-R@1结果复现不到论文这么高 差十多正常吗

你可以看看这里的回复。https://github.com/zjukg/Structure-CLIP/issues/5
