### ISSUE TITLE
About TextRank1 result and ImageRank1 result

### ISSUE THREAD

**Issue by ghost** [zjukg/Structure-CLIP#13]
Why do my experiment results show that TextRank1 is closer to IR-R@1 in Table 1 in the paper, while ImageRank1 is closer to TR-R@1 in Table 1 in the paper? Or is that the way it should be? Hope to reply, thank you!

**Comment by BigHyf** [comment]
你好，非常感谢你指出这个问题，是我们在写论文表格的时候表头出现了一些小问题，应该将IR-R@1和TR-R@1换一下，我们后续会修正，所以你的结果应该没有问题。TextRank@1是41.2，ImageRank@1是55.6，这个recall的结果可以看arxiv版本的附录部分。
