### ISSUE TITLE
About Vit-L/14 and A100-80GB 

### ISSUE THREAD

**Issue by ghost** [zjukg/Structure-CLIP#14]
Excuse me, why can't I run Vit-L/14 with A100-80GB GPU? What GPU was the author using at the time?

**Comment by lichong0** [comment]
> 请问一下，为什么不能使用 A100-80GB GPU 运行 Vit-L/14？作者当时使用什么GPU？

@lucas0214 老师您好，请问数据集您下载了吗，链接失效了。

**Comment by BigHyf** [comment]
印象里我们的机器也是A100-80GB，可以考虑调整一下batch size
