### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by lichong0** [zjukg/Structure-CLIP#19]
@hackerchenzhuo @BigHyf  Hello Author ，The link of the dataset is invalid

**Comment by matheustmattioli** [comment]
Hi, I'm having the same issue.  Could the authors provide a new link please?

**Comment by BigHyf** [comment]
Baidu Cloud does not know why it is not available, the dataset we have updated through Google cloud disk.

**Comment by matheustmattioli** [comment]
Thank you very much
