### ISSUE TITLE
about the dataset?

### ISSUE THREAD

**Issue by ZHUXUHAN** [zjukg/Structure-CLIP#3]
can you provide the training datasets details, what is the 100k data? If the details of this dataset setting are not made available, it seems challenging to follow this work.

**Comment by hackerchenzhuo** [comment]
We will provide you with the data as soon as possible @BigHyf, thanks for your question

**Comment by BigHyf** [comment]
Here we provide the specific data link. Since I have left the company, this data was copied on the server by mentor. I hope it will be helpful to you.

链接：https://pan.baidu.com/s/1-ZpEZQfOP5byKmNRmHAeaA 
提取码：2oz1

**Comment by hackerchenzhuo** [comment]
@ZHUXUHAN Do you have any other problems?

**Comment by ZHUXUHAN** [comment]
> @ZHUXUHAN Do you have any other problems?
Thank you very much for your answer, which helps me a lot.

**Comment by gyhhe** [comment]
Baidu.com link is not available, can you send it again, thanks!

**Comment by wdi-nancy** [comment]
> Here we provide the specific data link. Since I have left the company, this data was copied on the server by mentor. I hope it will be helpful to you.
> 
> 链接：https://pan.baidu.com/s/1-ZpEZQfOP5byKmNRmHAeaA 提取码：2oz1

The link is invalid.
